//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputSystem/RoverControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RoverControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RoverControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RoverControl"",
    ""maps"": [
        {
            ""name"": ""RoverBaseControl"",
            ""id"": ""ad8cd68f-b748-4a7c-b4d5-9d9f622cb952"",
            ""actions"": [
                {
                    ""name"": ""MoveForward"",
                    ""type"": ""Button"",
                    ""id"": ""e53a2924-e965-4e19-a235-54a860d30ff1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5667319d-12f2-4d20-9f49-2c54dac372eb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RoverBaseControl
        m_RoverBaseControl = asset.FindActionMap("RoverBaseControl", throwIfNotFound: true);
        m_RoverBaseControl_MoveForward = m_RoverBaseControl.FindAction("MoveForward", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RoverBaseControl
    private readonly InputActionMap m_RoverBaseControl;
    private List<IRoverBaseControlActions> m_RoverBaseControlActionsCallbackInterfaces = new List<IRoverBaseControlActions>();
    private readonly InputAction m_RoverBaseControl_MoveForward;
    public struct RoverBaseControlActions
    {
        private @RoverControl m_Wrapper;
        public RoverBaseControlActions(@RoverControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveForward => m_Wrapper.m_RoverBaseControl_MoveForward;
        public InputActionMap Get() { return m_Wrapper.m_RoverBaseControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RoverBaseControlActions set) { return set.Get(); }
        public void AddCallbacks(IRoverBaseControlActions instance)
        {
            if (instance == null || m_Wrapper.m_RoverBaseControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RoverBaseControlActionsCallbackInterfaces.Add(instance);
            @MoveForward.started += instance.OnMoveForward;
            @MoveForward.performed += instance.OnMoveForward;
            @MoveForward.canceled += instance.OnMoveForward;
        }

        private void UnregisterCallbacks(IRoverBaseControlActions instance)
        {
            @MoveForward.started -= instance.OnMoveForward;
            @MoveForward.performed -= instance.OnMoveForward;
            @MoveForward.canceled -= instance.OnMoveForward;
        }

        public void RemoveCallbacks(IRoverBaseControlActions instance)
        {
            if (m_Wrapper.m_RoverBaseControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRoverBaseControlActions instance)
        {
            foreach (var item in m_Wrapper.m_RoverBaseControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RoverBaseControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RoverBaseControlActions @RoverBaseControl => new RoverBaseControlActions(this);
    public interface IRoverBaseControlActions
    {
        void OnMoveForward(InputAction.CallbackContext context);
    }
}
